services:
  api: 
    image: matheushpr9/ordine-api-app:v1.0.3
    command: go run main.go run
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      LOG_LEVEL: INFO
      ALLOWED_ORIGINS: localhost,https://test.com
    ports:
      - "8080:8080" # Posicione fora de deploy  

  database:
    image: matheushpr9/ordine-api-database:v1.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bob_live
      MYSQL_PASSWORD: pwdlocal
      MYSQL_DATABASE: ordine
      TZ: "America/Sao_Paulo"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      retries: 30
      start_period: 60s
      timeout: 5s
    ports:
      - "3306:3306" # Posicione fora de deploy

volumes:
  database: {}
