services:
  api:
    build:
      context: .
      dockerfile: build/go/Dockerfile
    command: go run main.go run
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      LOG_LEVEL: INFO
      ALLOWED_ORIGINS: localhost,https://test.com



  database:
    build:
      context: .
      dockerfile: build/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bob_live
      MYSQL_PASSWORD: pwdlocal
      MYSQL_DATABASE: ordine
      TZ: "America/Sao_Paulo"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      retries: 30
      start_period: 60s
      timeout: 5s
    ports:
      - "3306:3306"


  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8081:8080" 
    environment:
      - HOST=tasks.visualizer
      - PORT=8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"

volumes:
  database: {}